import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";
import { CONTACT_EMAIL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service — AI Chat Assistant",
  description: "The terms governing your use of AI Chat Assistant.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="June 17, 2026">
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of
        AI Chat Assistant (the &ldquo;Service&rdquo;). By signing in or otherwise using
        the Service, you agree to these Terms. If you do not agree, do not use the
        Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        AI Chat Assistant is a conversational application that lets you exchange
        messages with, and send documents and images to, third-party AI models
        (including Anthropic&rsquo;s Claude and, where configured, OpenAI and Groq) and
        receive AI-generated responses. The Service is provided for general,
        informational, and personal use.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 13 years old (or the minimum age of digital consent in
        your jurisdiction) to use the Service. By using it, you represent that you meet
        this requirement and that any information you provide is accurate.
      </p>

      <h2>3. Your account</h2>
      <p>
        You sign in using Google authentication via Firebase. You are responsible for
        activity that occurs under your account and for maintaining the security of the
        Google account you use to sign in. Notify us promptly of any unauthorized use.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Violate any law or the rights of others;</li>
        <li>
          Generate or distribute content that is unlawful, harmful, harassing, hateful,
          or that exploits or endangers others;
        </li>
        <li>
          Attempt to reverse engineer, disrupt, overload, or gain unauthorized access to
          the Service or its underlying providers;
        </li>
        <li>
          Upload content or files you do not have the right to share, or that contain
          malware; or
        </li>
        <li>
          Use outputs in any way that violates the usage policies of the underlying AI
          providers.
        </li>
      </ul>

      <h2>5. Your content</h2>
      <p>
        &ldquo;Your Content&rdquo; means the messages, prompts, and files you submit and
        the responses generated for you. As between you and us, you retain ownership of
        the inputs you provide. You grant us a limited license to process Your Content
        solely to operate and provide the Service &mdash; including transmitting it to
        the AI providers needed to generate a response. You are responsible for Your
        Content and for ensuring you have the rights to submit it.
      </p>

      <h2>6. AI-generated content</h2>
      <p>
        Responses are generated by automated models and may be{" "}
        <strong>inaccurate, incomplete, or misleading</strong>. The Service does not
        provide professional advice (legal, medical, financial, or otherwise). You are
        responsible for evaluating outputs before relying on or acting on them. Do not
        submit sensitive personal, confidential, or regulated information you are not
        comfortable sending to third-party AI providers.
      </p>

      <h2>7. Third-party services</h2>
      <p>
        The Service relies on third parties, including AI model providers (Anthropic,
        and where configured OpenAI and Groq) and Google Firebase for authentication and
        data storage. Your use of the Service is also subject to those providers&rsquo;
        terms and policies, and we are not responsible for their services.
      </p>

      <h2>8. Intellectual property</h2>
      <p>
        The Service&rsquo;s software, design, and branding are owned by us or our
        licensors and are protected by applicable laws. These Terms do not grant you any
        rights in them except the limited right to use the Service as permitted here.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        The Service is provided <strong>&ldquo;as is&rdquo;</strong> and{" "}
        <strong>&ldquo;as available&rdquo;</strong> without warranties of any kind,
        whether express or implied, including merchantability, fitness for a particular
        purpose, and non-infringement. We do not warrant that the Service will be
        uninterrupted, secure, or error-free, or that outputs will be accurate.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we will not be liable for any indirect,
        incidental, special, consequential, or punitive damages, or any loss of data,
        profits, or goodwill, arising from your use of the Service.
      </p>

      <h2>11. Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or terminate access
        if you violate these Terms or to protect the Service or its users. You can delete
        individual chats within the app at any time.
      </p>

      <h2>12. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be reflected
        by updating the &ldquo;Last updated&rdquo; date above. Your continued use of the
        Service after changes take effect constitutes acceptance of the revised Terms.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms? Contact us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
